### ISSUE TITLE
When updating to 2.2 ids and classes don't show up on pages anymore

### ISSUE THREAD

**Issue by toninummela** [billerickson/Div-Shortcode#1]
I just updated the plugin to 2.2 and after I save the page the div's classes don't show up on the page anymore. On the page they get transformed just to plain div-tags without ids or classes.

Editor's code still preserves the ids and classes, but somehow they get stripped off when rendering the page.

**Comment by billerickson** [comment]
Can you provide an example of the shortcode you're using in the backend, and what is displayed on the frontend?

**Comment by billerickson** [comment]
Ah I see the issue now, the variables changed. I'm fixing that right now - update should be out in a few minutes.
