### ISSUE TITLE
Plugin abandoned?

### ISSUE THREAD

**Issue by sdc-andy** [billerickson/Div-Shortcode#2]
The Wordfence site scan reports that this plugin "was last updated 3 years 2 months ago and tested up to WordPress 4.7.18".  

Has this plugin been abandoned and if so, what recommendations are there for alternatives?

-Andy.

**Comment by billerickson** [comment]
No, this plugin isn't abandoned, but it is feature-complete and not in need of updates.

I originally built this for creating multi-column content areas in the classic editor. There are better alternatives depending on your specific need.

If you're still using the classic editor, try [Column Classes](https://www.billerickson.net/using-column-classes/). If you're using the new block editor, use the Columns block that's built into core.
